theme: jekyll-theme-minimal
title: Team EEEL
description: A short description of your site's purpose
url: http://eeel.site
logo: /logo.png
#show_downloads: ["true"]
#google_analytics: [Your Google Analytics tracking ID]
