theme: jekyll-theme-minimal
title: Team EEEL
description: Process-driven Creative Startup
url: http://eeel.site
logo: /logo_512.png
#show_downloads: ["true"]
#google_analytics: [Your Google Analytics tracking ID]
